### ISSUE TITLE
KS.CFG L126: Largest Disk Capacity -> wrong variables?

### ISSUE THREAD

**Issue by stuerzi** [lamw/usb-to-sddc#2]
Hi William,

Thanks for the scripts and the work, its great =)

while debugging my setup if found, that on line 126 it should reference to 'largestDisk' and 'largestDiskSize' instead of 'diskId' and 'diskSize'. After i changed that, i got correct results on running multiple Disks.

Thanks

Patric

**Comment by lamw** [comment]
L126 is a print statement? https://github.com/lamw/usb-to-sddc/blob/master/KS.CFG#L126

**Comment by stuerzi** [comment]
sorry, its the syslog entry....

**Comment by lamw** [comment]
Sorry, I'm not sure I follow? Its a print statement, so not sure how that would get the right results and looking at it, its also correct. I'm printing the ID of the largest disk selected & its size.

**Comment by stuerzi** [comment]
actually you are logging the diskSize and diskId of the disk while looping through "for disk in result".

syslog entry states: "largest disk so far". in my case the last log was the small nvme ssd, not the storage ssd, if you loop down the vdq -q statement and nvme is listed after storage ssd, the log statement gets wrong, because my nvme is not the "largest disk so far".

**Comment by lamw** [comment]
> actually you are logging the diskSize and diskId of the disk while looping through "for disk in result".

Right, thats actually what I want as I'm not sure which is the "biggest", so it'll just pick the first and slowly compare. It looks like in your other note, the issue is trying to do string comparison rather than than int (which did cross my mind) and I suspect thats the actual issue

**Comment by lamw** [comment]
@stuerzi Just took a look at your fork and I now understand your changes. I've gone ahead and pushed that to my repo as well. Thanks for contribution
